baseURL: '/'
languageCode: 'en-us'
title: 'claesto'
theme: 'PaperModX'

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
#publishDir: "docs"

menu:
  main:
    - name: "Articles"
      url: "/archives/"
      weight: 10
    - name: Tags
      url: /tags/
      weight: 20
    - name: "About"
      url: "/about/"
      weight: 30
    - name: "🔍"
      url: "/search/"
      weight: 40
  
params:
  env: production
  author:
    - Tom Claessens
  description: "Explore a captivating mix of personal stories, thoughtful musings, and curious explorations. This blog dives into life’s unpredictable twists and turns—offering a little something for everyone. Join the journey and discover posts worth sticking around for."
  disableAnchoredHeadings: true
  disableSpecial1stPost: true
  EnableImageZoom: true
  noComments: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowWordCount: false
    
outputs:
  home:
    - HTML
    - RSS
    - JSON
